### ISSUE TITLE
travis should fail if nop-server builr or test fails

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/nopol#101]

**Comment by surli** [comment]
Should be reopened: it's not fixed yet, see https://travis-ci.org/SpoonLabs/nopol/jobs/201512772

> Running nopol server
> ./.travis_run_tests.sh: line 27: cd: nopol-server: No such file or directory
> [INFO] Scanning for projects...

**Comment by monperrus** [comment]
closing?

**Comment by surli** [comment]
Yep.
