### ISSUE TITLE
bug: two instances of Nopol cannot run in parallel with Gzoltar

### ISSUE THREAD

**Issue by surli** [SpoonLabs/nopol#129]
Gzoltar fault localizer create launch agents using a static field to the jar to launch, so there's some concurrential access issues when doing that. 
It explains ZipException obtained in librepair, it could cause some issues in nopol-server too.

**Comment by monperrus** [comment]
I'd say that Librepair should use the other fault localization mode made based on Cocospoon.

**Comment by surli** [comment]
> I'd say that Librepair should use the other fault localization mode made based on Cocospoon.

I'm currently testing it with this fault localization, but according to @tdurieux it's slower.

**Comment by surli** [comment]
Gzoltar is using a static target path to create a patch for launching its agent, which could create a bug when running in parallel Nopol. 
The solution is to simply don't use Gzoltar but CocoSpoon (Ochiai) Fault localizer in that case.
