### ISSUE TITLE
tools.jar not visible from NOPOL running "java -jar"wise

### ISSUE THREAD

**Issue by agodio** [SpoonLabs/nopol#141]
Hello

I've installed NOPOL on a fresh installation of Linux Mint, following the README. I was able to run the example of the README, but I wasn't with the option:

`-y dynamoth`

Even adding tools.jar on the classpath (-c) I get this error

`For using Dynamoth, you must add tools.jar in your classpath from your installed jdk`

Finally, after digging this repo, I found I can run NOPOL in this way

`java -cp $JAVA_HOME/lib/tools.jar:../nopol/target/nopol-0.2-SNAPSHOT-jar-with-dependencies.jar fr.inria.lille.repair.Main <nopol arguments>`

and it worked.

**Comment by monperrus** [comment]
Thanks a lot for the feedback. Changed the readme accordingly: https://github.com/SpoonLabs/nopol/commit/e81634a3967794969d07076db9035438159aaaa3
