### ISSUE TITLE
.diff not generated when argument -s starts with "./"

### ISSUE THREAD

**Issue by agodio** [SpoonLabs/nopol#142]
Calling Nopol with the argument -s starting with "./", e.g

`-s ./src/main/java/`

instead of

`-s src/main/java/`

produces an empty .diff file.

The reason:

```
private String getClassPath(CtType type) {
		String path = type.getPosition().getFile().getPath();
		String intersection = null;
		File[] inputSources = nopolContext.getProjectSources();
		for (int i = 0; i < inputSources.length; i++) {
			File inputSource = inputSources[i];
			if (intersection == null) {
				intersection = inputSource.getPath();
			} else {
				intersection = intersection(intersection, inputSource.getPath());
			}
		}
		int indexOfIntersection = path.indexOf(intersection);

		if (indexOfIntersection != -1) {
			return path.substring(indexOfIntersection);
		} else {
			return null;
		}
	}
```

`int indexOfIntersection = path.indexOf(intersection);`

At this point path is the full path to the .java file, e.g "/Users/user/src/main/Main.java"
and intersection is the argument passed with -s, e.g "./src/main/java"

Clearly intersection is not a substring of path, so indexOf returns -1. Finally getClassPath returns null.

GNU find return paths starting with "./" by default. Sanitising this string will improve the "scriptability" of Nopol.

**Comment by tdurieux** [comment]
Thanks for the issue, I will fix it next week.

**Comment by tdurieux** [comment]
close with bec15dfb3962815ab32e98dfec0c17e3e406143e
