### ISSUE TITLE
Problem to repair Chart_3

### ISSUE THREAD

**Issue by DehengYang** [SpoonLabs/nopol#143]
When I run Nopol with command given in "https://github.com/SpoonLabs/nopol/blob/master/.travis_run_defects4j.sh" to repair Chart_3 in Defect4J, I get the valid patch, which is supposed to repair the two failing test cases, as follow:
![chart_3_patch](https://user-images.githubusercontent.com/32570286/32258261-82d8835c-bef4-11e7-8958-3c4fb0b7b0bb.png)

Before I repair the Chart_3, the failing test cases are:
`Failing tests: 2
  - org.jfree.data.time.junit.MonthTests::testParseMonth
  - org.jfree.data.time.junit.TimeSeriesTests::testCreateCopy3`

After I get the valid patch produced by Nopol, I apply the patch into Chart_3 project, in order to see if the failing tests will be eliminated. But the results are not as good as what I expected before:
I run "defetcs4j compile" and "defects4j test"
then I got:
![repaired_chart_3_failing tests](https://user-images.githubusercontent.com/32570286/32258354-05f6fae8-bef5-11e7-9d31-217bfd96e8b8.png)

There are still failing tests.

This is quite confusing. Any help or hints will be much appreciated.

Thanks.

**Comment by DehengYang** [comment]
I think I have already figured this out. It was because I set the system language of my 14.04 Ubuntu to Chinese, which directly leaded to the assertion of the month "March" failed.

Sorry for my disturbing. Thank you.

**Comment by monperrus** [comment]
For the record, there are two things to check to be able to repair Chart3:

* the system language: must be English
* the JVM: must be Java 7
