### ISSUE TITLE
What is the function of "mvn package -DskipTests"?

### ISSUE THREAD

**Issue by Kaka727** [SpoonLabs/nopol#144]
On my computer, the order "mvn package -DskipTests" didn't work out, just like this
![1](https://user-images.githubusercontent.com/33283686/32273190-64a1957a-bf3c-11e7-886d-3d53459dc921.PNG)
But the program can still find out and fix the bug, just like this
![2](https://user-images.githubusercontent.com/33283686/32273209-7b84f6d8-bf3c-11e7-87a9-90f7cdff9ac7.PNG)
So what is the function of "mvn package -DskipTests"?

**Comment by monperrus** [comment]
> So what is the function of "mvn package -DskipTests"?
To compile the application and the tests.

**Comment by Kaka727** [comment]
font{
        line-height: 1.7;
    }


    
But as you can see, I didn't compile them correctly, but they could still work out the bug.Why could this happen?And how could I fix this error?



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 11/1/2017 20:54，Martin Monperrus<notifications@github.com> wrote： 


> So what is the function of "mvn package -DskipTests"?
To compile the application and the tests.

**Comment by monperrus** [comment]
This error happens because Cocospoon is not installed locally.

> |git clone https://github.com/SpoonLabs/CoCoSpoon.git cd CoCoSpoon mvn clean install|

**Comment by Kaka727** [comment]
Ok,I got it.
Thank you very much
