### ISSUE TITLE
bug in fault localization using cocospoon "--flocal cocospoon" 

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/nopol#148]
When the "--flocal cocospoon" flag, Nopol sometimes fails because of a [CocoSpoon](https://github.com/SpoonLabs/CoCoSpoon) bug.

This happens for the Chart bugs of Defects4J.

**Comment by monperrus** [comment]
@DehengYang would you give a try to fix this?

**Comment by DehengYang** [comment]
Yes, I am trying to fix it. When I have the solution, I will report it immediately. Thank you for your support!

**Comment by monperrus** [comment]
Thanks!

**Comment by monperrus** [comment]
seems fixed in last version
