### ISSUE TITLE
Deploy a first release version of Nopol

### ISSUE THREAD

**Issue by surli** [SpoonLabs/nopol#156]
We're currently using Nopol in production on Repairnator with the version number 0.2-SNAPSHOT, which is pushed on @tdurieux Maven repository. 

But currently a new snapshot is pushed for each successful commit on the repository. I just had Repairnator broken because a new version has been pushed this morning.

I suggest then to deploy a first release of Nopol, maybe on Maven Central, on which we can rely for Repairnator and other tools.

**Comment by monperrus** [comment]
What was the breakage?

**Comment by surli** [comment]
Hmmm apparently the bug wasn't coming from Nopol, my bad. However, I remain convinced that it would be a good idea to have a release of Nopol to avoid unexpected behaviour changes for Repairnator.

**Comment by monperrus** [comment]
Just deployed cede74c7247ab1b6322f32a2665c7974120d6089 (version number = commit SHA) as "release" and not "snapshot" on Thomas' repo: https://github.com/tdurieux/maven-repository/tree/master/releases/fr/inria/gforge/spirals/nopol

If you depend on it, it won't change in the future
