### ISSUE TITLE
About using noclasspath

### ISSUE THREAD

**Issue by surli** [SpoonLabs/nopol#159]
We got a lot of new errors when using recent version of Nopol on complex project, and this because of Spoon (see: https://github.com/Spirals-Team/repairnator/issues/445)

This seems directly related to the change made in https://github.com/SpoonLabs/nopol/commit/8ad3dad85d0b6a2ad896d40cbb23c6d4becfe1bc#diff-853ae1db6765413a0c0f98dbad2405cd on the try/catch removal on `SpoonModelLibrary.java`.

Regarding the high number of errors we got, I wonder if it could be a good fix to use noClasspath mode with Spoon. WDYT?

**Comment by monperrus** [comment]
the good news is that before that change, it didn't work either, it was just a silent error.

setting nopol in noclasspath maybe an option, but with no guarantee whatsoever (complex transformations in noclasspath ... may fail miserably).

another option, less workaround, is that repairnator correctly collects the classpath of the project under repair, typically with:

    mvn -q dependency:build-classpath  

and passes it to Nopol

**Comment by surli** [comment]
> the good news is that before that change, it didn't work either, it was just a silent error.

Absolutely!

> another option, less workaround, is that repairnator correctly collects the classpath of the project under repair, typically with:

It's already what I do.
Full story: the project I tested fails because of a problem with the logger, it passes if you give the whole classpath AND you set noClasspath to true... 

Maybe a middleway is to provide an option in Nopol to use Spoon in noclasspath and to trigger a warning when it's used... 

EDIT: I opened an issue on Spoon about that: https://github.com/INRIA/spoon/issues/1911

**Comment by monperrus** [comment]
does it mean that the classpath you collect is incomplete?

**Comment by surli** [comment]
> does it mean that the classpath you collect is incomplete?

Nop it's another issue I think. I got the classpath using `mvn dependency:build-classpath`

**Comment by monperrus** [comment]
can it be the Javac/JDT incompatibility issue then?

**Comment by surli** [comment]
I get back on this issue: I don't have an answer to your last question.
However we change the behaviour of Spoon on the current snapshot to be in noClasspath by default if the `setNoclasspath` is not called: so if you want to keep being in full-classpath mode in Nopol in the future version of Spoon, you **need** to set the boolean to false.

**Comment by surli** [comment]
Nopol has been upgraded to Spoon 7.0.0 and works well. Closing this one.
