### ISSUE TITLE
problem using intellij plugin

### ISSUE THREAD

**Issue by vitogreco** [SpoonLabs/nopol#162]
Hi i'm trying to use the plugin but it keeps sending this err when using the nopol fix on the toy project "The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 107,4,main]"
 
currently using IJ 2016.3.8
and java sdk 1.7

any sugestions is apreciated

**Comment by monperrus** [comment]
Thanks for bug report. @danglotb would you be able to help @vitogreco

**Comment by monperrus** [comment]
did you find a solution to your problem?
