### ISSUE TITLE
`mvn clean install` failed in jdk 1.7 when installing cocospoon

### ISSUE THREAD

**Issue by DehengYang** [SpoonLabs/nopol#178]
Sorry for interrupt you with this issue. I met a problem when I was trying to configure Nopol in my Ubuntu 14.04 computer, and I would like to present the details here.

First, I downloaded `CoCospoon` using git according to the README. Note that in the pom.xml of CoCospoon, the required jdk version is 1.7, so I set my jdk version as 1.7. However, when I ran `mvn clean install` in the folder of CoCospoon, the error occured:

![image](https://user-images.githubusercontent.com/32570286/51478562-a3849b80-1d40-11e9-84ff-199de681b4b7.png)

I thought the main info about this error is `Unsupported major.minor version 52.0`. Therefore, I change the java version into 1.8, and ran the `mvn clean install` again. This time, the cocospoon is successfully installed into the maven repo. Futhermore, I found that the current version of Nopol requires jdk 1.8, while the previous Nopol version (e.g., at March 20 2017) required jdk 1.7. Meanwhile, the README that guides us to use jdk 1.7 puzzles me to a certain extent.

So I would like to ask that whether the current Nopol and cocospoon all requires jdk 1.8 instead of jdk 1.7 pointed out in README file, and whether the current Nopol requiring jdk 1.8 could deal with the defects4j buggy programs which requires jdk 1.7.

Any help would be much appreciated.

**Comment by monperrus** [comment]
> Note that in the pom.xml of CoCospoon, the required jdk version is 1.7
No, it's the compatibility of the source version and the bytecode version, not the compatibility of
the JDK version.

Yet CocoSpoon cannot be built on Java 7, see https://github.com/SpoonLabs/CoCoSpoon/pull/4. Branch
compat-java7 may be a valid workaround, could you mvn-install this branch and try again?

**Comment by DehengYang** [comment]
Thank you so much for your prompt reply!

I downloaded the `compat-java7` branch using command `git clone -b compat-java7 https://github.com/SpoonLabs/CoCoSpoon.git`. Then I check the version of cocospoon and jdk in my computer: 

> dale@deheng:\~/CoCoSpoon$ git branch
> \* compat-java7
> dale@deheng:\~/CoCoSpoon$ java -version
> java version "1.7.0_80"
> Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
> Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

After that, I ran `mvn clean install`, but this time the error is :

> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.153 sec
> Running fil.iagl.opl.cocospoon.CocoSpoonTest
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.254 sec <<< FAILURE!
> test(fil.iagl.opl.cocospoon.CocoSpoonTest)  Time elapsed: 1.246 sec  <<< ERROR!
> java.lang.UnsupportedClassVersionError: fil/iagl/opl/cocospoon/samples/MethodSample : Unsupported major.minor version 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at spoon.support.reflect.declaration.CtClassImpl$NewInstanceClassloader.loadClass(CtClassImpl.java:288)
> 	at spoon.support.reflect.declaration.CtClassImpl.newInstance(CtClassImpl.java:273)
> 	at fil.iagl.opl.cocospoon.CocoSpoonTest.test(CocoSpoonTest.java:41)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
> 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
> 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
> 
> 
> Results :
> 
> Tests in error: 
>   test(fil.iagl.opl.cocospoon.CocoSpoonTest): fil/iagl/opl/cocospoon/samples/MethodSample : Unsupported major.minor version 52.0
> 
> Tests run: 13, Failures: 0, Errors: 1, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 15.515 s
> [INFO] Finished at: 2019-01-22T16:46:51-08:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project CocoSpoon: There are test failures.

It seems that the compatibility problem still exists.

I am so sorry that I am still not familar with maven projects, which restricts me in changing the pom.xml or source code. (This inspires me to learn more about maven and java projects). But I find the `CocoSpoon-1.0.0-SNAPSHOT-jar-with-dependencies.jar` that was previously installed under jdk 1.7 and backed up in my computer in 2017. This jar is available in jdk 1.7, thus being my current workaround... 

Thank you again for your help! 👍

**Comment by monperrus** [comment]
In CoCoSpoon, please do "mvn install -DskipTests".

**Comment by DehengYang** [comment]
It really works after `mvn install -DskipTests`.

Thank you!

**Comment by monperrus** [comment]
great!
