### ISSUE TITLE
Installation question: SMT solver and nopol

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/nopol#181]
> Hi Martin,

> After reading up on Nopol. I was wondering if you would be able to provide clarification of the requirement: SMT Solver.

> It is noted on GitHub that this (SMT) is required to test & run Nopol, but I am unable to find where to download SMT Solver.

> Jacob Yanicak

**Comment by monperrus** [comment]
Hi Jacob,
By default, Nopol uses the Z3 solver that can be downloaded at:
https://www.microsoft.com/en-us/download/details.aspx?id=52270  
https://github.com/Z3Prover/z3
Best, --Martin

**Comment by yanicakj** [comment]
Thanks again Martin
