### ISSUE TITLE
How to solve the problem "Received fatal alert: protocol_version"?

### ISSUE THREAD

**Issue by sunshine-lcc** [SpoonLabs/nopol#184]
I met the problem when I ran "mvn test" in the directory /nopol-master/nopol
Could you please tell me how to solve it?
It seems that it has a relation with TLS or SSL wrong

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46.692 s
[INFO] Finished at: 2019-07-20T22:16:56+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nopol: Could not resolve dependencies for project fr.inria.gforge.spirals:nopol:jar:0.2-SNAPSHOT: The following artifacts could not be resolved: junit:junit:jar:4.11, org.reflections:reflections:jar:0.9.9-RC1, org.javassist:javassist:jar:3.16.1-GA, dom4j:dom4j:jar:1.6.1, xml-apis:xml-apis:jar:1.0.b2, com.google.guava:guava:jar:15.0, ch.qos.logback:logback-classic:jar:1.0.13, ch.qos.logback:logback-core:jar:1.0.13, org.slf4j:slf4j-api:jar:1.7.5, com.google.code.findbugs:jsr305:jar:2.0.1, org.hamcrest:hamcrest-core:jar:1.3, fr.inria.gforge.spoon:spoon-core:jar:7.0.0, org.eclipse.jdt:org.eclipse.jdt.core:jar:3.13.102, org.eclipse.platform:org.eclipse.core.resources:jar:3.13.400, org.eclipse.platform:org.eclipse.core.expressions:jar:3.6.400, org.eclipse.platform:org.eclipse.core.runtime:jar:3.15.300, org.eclipse.platform:org.eclipse.osgi:jar:3.14.0, org.eclipse.platform:org.eclipse.equinox.common:jar:3.10.400, org.eclipse.platform:org.eclipse.core.jobs:jar:3.10.400, org.eclipse.platform:org.eclipse.equinox.registry:jar:3.8.400, org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.7.400, org.eclipse.platform:org.eclipse.core.contenttype:jar:3.7.300, org.eclipse.platform:org.eclipse.equinox.app:jar:1.4.200, org.eclipse.platform:org.eclipse.core.filesystem:jar:1.7.400, org.eclipse.platform:org.eclipse.text:jar:3.8.200, org.eclipse.platform:org.eclipse.core.commands:jar:3.9.400, com.martiansoftware:jsap:jar:2.1, log4j:log4j:jar:1.2.17, commons-io:commons-io:jar:2.5, org.apache.maven:maven-model:jar:3.3.9, org.codehaus.plexus:plexus-utils:jar:3.0.22, org.apache.commons:commons-lang3:jar:3.5, com.fasterxml.jackson.core:jackson-databind:jar:2.9.2, com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0, com.fasterxml.jackson.core:jackson-core:jar:2.9.2, commons-cli:commons-cli:jar:1.3, fil.iagl.cocospoon:CocoSpoon:jar:1.0.0-SNAPSHOT, com.cloudbees:diff4j:jar:1.2, org.json:json:jar:20160810: Could not transfer artifact junit:junit:jar:4.11 from/to tdurieux.github.io/maven-repository/snapshots/ (https://tdurieux.github.io/maven-repository/snapshots/): Received fatal alert: protocol_version -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by monperrus** [comment]
`mvn -Dhttps.protocols=TLSv1.2 test`

see https://stackoverflow.com/questions/50824789/why-am-i-getting-received-fatal-alert-protocol-version-or-peer-not-authentic/50924208#50924208

Best regards, --Martin
