### ISSUE TITLE
Using Nopol to properly assess / repair JDK 1.7 projects, such as Defect4J projects

### ISSUE THREAD

**Issue by ProdigyXable** [SpoonLabs/nopol#192]
How would one use nopol on a java 7 project? Currently, I can execute nopol successfully with java 8 but projects which explicitly depend on java 7 will have an incorrect set of originally failing / passing test suites. As an example, executing nopol on Defect4J Lang-1 via JDK 1.8 has initially 9 failing test cases when there should be only 1 failing test case. Because of this discrepancy, I'd like to avoid this at all costs.

Because of this, it makes sense to compile / execute nopol with JDK 1.7. When building + executing with Java 1.7 however, I receive a **spoon/processing/"Processor" : Unsupported major.minor version 52.0 nopol**. When I further looked into this dependency, it seems like it is compatible with only with JDK 1.8+, 

The next option might be to download an older version of Nopol which executed on JDK 1.7 already. After downloading a known JDK7 compatible release of Nopol (March2017 branch), some dependencies become unfetchable / unresolvable..

After examining the current code, I also see no already existing place where you can execute with JDK 1.8 but test with JDK 1.7, as can be done in astor.

Thus, how might I test with JDK 1.7 within Nopol while using JDK 1.8? Let me know of which specific error logs / execution results you would like me to post.

**Comment by monperrus** [comment]
This is a tricky problem. There are three components:
* the JDK version used to compile Nopol
* the JDK version used to compile the project under repair
* the JDK version used to run the repair process

Nopol, even built with Java 8, can repair Java 7 code (a JVM 8 can execute Java 7 bytecode).

It is known that some bugs in Defects4J are not compatible with Java8, my recommendation is to discard those ones.
