### ISSUE TITLE
Command line argument --test

### ISSUE THREAD

**Issue by jose** [SpoonLabs/nopol#198]
Hi,

As defined in section [Minimal Usage](https://github.com/SpoonLabs/nopol#minimal-usage), `-t|--test` _"Defines the tests of the project"_. Are these "tests" test classes or test cases/methods?  And, should failing and non-failing tests be provided, or just failing tests?

--
Best,
Jose

**Comment by monperrus** [comment]
The test argument is passed to NopolContext (`new NopolContext(sourceFiles, classpath, jsapConfig.getStringArray("test"))`)

where the constructor reads `NopolContext(File[] sourceFile, URL[] classpath, String[] testClasses)`

So the first answer is "test classes".

> should failing and non-failing tests be provided

All tests that you want to consider for a plausible patch. Nopol will identify the failing test methods in those test classes by running them.

**Comment by monperrus** [comment]
Clarified argument in #201

**Comment by jose** [comment]
Thanks @monperrus.
