### ISSUE TITLE
add support for desactivating Gzoltar

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/nopol#22]

**Comment by monperrus** [comment]
Map&lt;SourceLocation, List&lt;TestResult>>
interface TestResult {
TestCase getTestCase()
boolean isSuccessful()
}

DumbFaultLocalizer: list of executed statements with no specific order -- potentially non deterministic (implem uses CocoSpoon)

GZoltarFaultLocalizer: previous implementation

CocoSpoonBasedSpectrumBasedFaultLocalizer: list of executed statements ordered by suspiciousness metric

OchiaiFaultLocalizer extends CocoSpoonBasedSpectrumBasedFaultLocalizer(Ochiai)
list of executed statements ordered by Ochiai suspiciousness
(will be the default one)
- one test for each :-)

**Comment by danglotb** [comment]
Our current implementation of Fault Localization with CoCoSpoon does not support junit < 4 because of it is based on the Annotation Test on test methods.

Please use "-z gzoltar" option until this issue is fixed.
