### ISSUE TITLE
collect more data in SMT mode

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/nopol#39]
Ariel:
I know NOPOL collects the values of all local variables, method parameters, and class fields that are typed with a basic primitive type, but what about public fields of locally defined objects?

```
class MyClass{
  public int value;
}

foo(){
  MyClass bar = new MyClass();
  bar.value = <any value from anywhere>
  //int nopolHack = bar.value;
  ...
}
```

the value of bar.value wouldn't be collected unless I uncomment the last assignment. How can I make NOPOL collect this data?

**Comment by monperrus** [comment]
Ariel, could you try in brutpol/dynamoth mode first? 

```
  [(-y|--synthesis) <smt|brutpol>]
        Define the patch synthesis. (default: smt)
```

**Comment by agodio** [comment]
My fault. I don't know how I get to that conclusion. Probably some interference from the paper or I missunderstood a log.

actually NOPOL does collect this data.

Closed for me.

**Comment by monperrus** [comment]
the data collection is different in SMT mode or in Dynamoth mode.

Did you check against both modes?

**Comment by agodio** [comment]
I only run NOPOL in smt mode, and it was able to synthesize patches which access this values.
