### ISSUE TITLE
Unneeded remove in SpecificationTestCasesListener

### ISSUE THREAD

**Issue by agodio** [SpoonLabs/nopol#47]
On src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java:80/84

The field inconsistentInputs is accessed through the self reference this, but it should be accessed using the corresponding getter, like all accesses to consistentInputs, which use consistentInputs().

**Comment by agodio** [comment]
Actually I think there is no need for removing inputs from consistentInputs at

src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java:81

because addToSpec adds an input to consistentInputs only if it is the first we add or there is no mapping for input but its keySet is equal to this.key

`(reference == null && this.keys.equals(inputs.keySet()))`

In other words the "hidden" invariant is: all the inputs in consistentInputs share the same keySet, so under the following condition

 `(!this.keys.equals(inputs.keySet()))`

consistentInputs can't have a mapping for inputs. 

is it right?

**Comment by monperrus** [comment]
Hi Ariel,

> In other words the "hidden" invariant is: all the inputs in consistentInputs share the same keySet

Yes

> consistentInputs can't have a mapping for inputs. 
>  I think there is no need for removing inputs from consistentInputs 

Of course :-)

Thanks,

--Martin
